name: Test App
on:
  # or workflow_dispatch
  # or [push, workflow_dispatch]
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    branches:
      # only for branches named feature/...
      - 'feature/**'
    types: [opened, edited, reopened]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Get repository code using github action - actions/checkout@v3
      - name: Get repository code
        uses: actions/checkout@v3
      # Add cache deps to increase job speed
      - name: Cache deps
        uses: actions/cache@v3
        with:
          # "~/" - default ubuntu path
          path: ~/.npm
          # hashFiles('**/package-lock.json') - check valid cache or not
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      # Install dependecies using
      - name: Install dependecies
        run: npm ci
      # Run lint
      - name: Lint application
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          # "~/" - default ubuntu path
          path: ~/.npm
          # hashFiles('**/package-lock.json') - check valid cache or not
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependecies
        run: npm ci
      # Run tests
      - name: Test application
        run: npm run test
  build:
    # waiting for dependent jobs to complete successfully before running the current job
    needs: [lint, test]
    # continue if job failed
    # continue-on-error: true
    strategy:
      # add some allies
      matrix:
        node_versions: [14, 16]
        use_os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.use_os }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_versions }}
      - name: Cache deps
        uses: actions/cache@v3
        with:
          # "~/" - default ubuntu path
          path: ~/.npm
          # hashFiles('**/package-lock.json') - check valid cache or not
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependecies
        run: npm ci
      # Build
      - name: Build application
        run: npm run build
      # Save Builded project to use in Deploy
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build_name
  deploy:
    # Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Get builded project
      - name: Get builded application
        uses: actions/download-artifact@v3
        with:
          name: build_name
